appName: "bppClientService"
log:
  level: debug
  destinations:
    - type: stdout
  context_keys:
    - transaction_id
    - message_id
http:
  port: 8080
  timeout:
    read: 30
    write: 30
    idle: 30
plugin:
  root: extracted/plugins
  pluginZipPath: plugins_bundle.zip
  plugins:
    - publisher
    - nopschemavalidator
    - router
    - nopsigner
    - nopsignvalidator
    - reqpreprocessor
    - gcpAuthMdw
module:
  modules:
    - name: transactionReciever
      path: /reciever
      targetType: msgQ
      plugin:
        schemaValidator:
          id: nopschemavalidator
        signValidator:
          id: nopsignValidator
        publisher:
          id: publisher
          config:
            project: ondc-seller-dev
            topic: clientSideTopic
        Router:
          id: router
          config:
            routingConfigPath: configs/bppRecieverRouting-config.yaml
        preProcessors:
          - id: reqpreprocessor
    - name: transactionCaller
      path: /caller
      targetType: "http"
      plugin:
        signer:
          id: nopsigner
        Router:
          id: router
          config:
            routingConfigPath: configs/bppCallerRouting-config.yaml
        preProcessors:
          - id: reqpreprocessor
        postProcessors:
          - id: gcpAuthMdw
            config:
              audience: "target"

