routingRules:
  - domain: ONDC:TRV10
    version: 2.0.0
    targetType: publisher
    target:
      publisherId: bapNetworkReciever
    endpoints:
      - search
      - select
      - init
      - confirm
      - status
      - update
      - cancel