appName: "onix"
log:
  level: debug
  destinations:
    - type: stdout
  contextKeys:
    - transaction_id
    - message_id
    - subscriber_id
http:
  port: 8080
  timeout:
    read: 30
    write: 30
    idle: 30
pluginManager:
  root: /app/plugins
  remoteRoot: /mnt/gcs/plugins/plugins_bundle.zip
modules:
  - name: bapTxnReciever
    path: /bap/reciever/
    handler:
      type: std
      registryUrl: https://onix-demo-adapter-593887498345.asia-south1.run.app/reg
      plugins:
        keyManager:
          id: secretskeymanager
          config:
            projectID: trusty-relic-370809
        cache:
          id: redis
          config:
            addr: 10.81.192.4:6379
        schemaValidator:
          id: nopschemavalidator
        signValidator:
          id: signvalidator
        publisher:
          id: publisher
          config:
            project: trusty-relic-370809
            topic: bapNetworkReciever
        router:
          id: router
          config:
            routingConfigPath: /mnt/gcs/configs/bapTxnReciever-routing.yaml
        middleware:
          - id: reqpreprocessor
            config:
              uuidKeys: transaction_id,message_id
              role: bap
      steps:
        - validateSign
        - addRoute
        - validateSchema
  - name: bapTxnCaller
    path: /bap/caller/
    handler:
      type: std
      registryUrl: https://onix-demo-adapter-593887498345.asia-south1.run.app/reg
      plugins:
        keyManager:
          id: secretskeymanager
          config:
            projectID: trusty-relic-370809
        cache:
          id: redis
          config:
            addr: 10.81.192.4:6379
        schemaValidator:
          id: nopschemavalidator
        signer:
          id: signer
        publisher:
          id: publisher
          config:
            project: trusty-relic-370809
            topic: bapNetworkReciever
        router:
          id: router
          config:
            routingConfigPath: /mnt/gcs/configs/bapTxnCaller-routing.yaml
        middleware:
          - id: reqpreprocessor
            config:
              uuidKeys: transaction_id,message_id
              role: bap
      steps:
        - validateSchema
        - addRoute
        - sign
  - name: bapSubscribeCaller
    path: /bap/subscribe
    handler:
      type: npSub
      registryUrl: https://onix-demo-adapter-593887498345.asia-south1.run.app/reg
      plugins:
        keyManager:
          id: secretskeymanager
          config:
            projectID: trusty-relic-370809
        cache:
          id: redis
          config:
            addr: 10.81.192.4:6379
  - name: bppTxnReciever
    path: /bpp/reciever/
    handler:
      type: std
      registryUrl: https://onix-demo-adapter-593887498345.asia-south1.run.app/reg
      plugins:
        keyManager:
          id: secretskeymanager
          config:
            projectID: trusty-relic-370809
        cache:
          id: redis
          config:
            addr: 10.81.192.4:6379
        schemaValidator:
          id: nopschemavalidator
        signValidator:
          id: signvalidator
        publisher:
          id: publisher
          config:
            project: trusty-relic-370809
            topic: bapNetworkReciever
        router:
          id: router
          config:
            routingConfigPath: /mnt/gcs/configs/bppTxnReciever-routing.yaml
        middleware:
          - id: reqpreprocessor
            config:
              uuidKeys: transaction_id,message_id
              role: bpp
      steps:
        - validateSign
        - addRoute
        - validateSchema
  - name: bppTxnCaller
    path: /bpp/caller/
    handler:
      type: std
      registryUrl: https://onix-demo-adapter-593887498345.asia-south1.run.app/reg
      plugins:
        keyManager:
          id: secretskeymanager
          config:
            projectID: trusty-relic-370809
        cache:
          id: redis
          config:
            addr: 10.81.192.4:6379
        schemaValidator:
          id: nopschemavalidator
        signer:
          id: signer
        publisher:
          id: publisher
          config:
            project: trusty-relic-370809
            topic: bapNetworkReciever
        router:
          id: router
          config:
            routingConfigPath: /mnt/gcs/configs/bppTxnCaller-routing.yaml
        middleware:
          - id: reqpreprocessor
            config:
              uuidKeys: transaction_id,message_id
              role: bpp
      steps:
        - validateSchema
        - addRoute
        - sign
  - name: bppSubscribeCaller
    path: /bpp/subscribe
    handler:
      type: npSub
      registryUrl: https://onix-demo-adapter-593887498345.asia-south1.run.app/reg
      plugins:
        keyManager:
          id: secretskeymanager
          config:
            projectID: trusty-relic-370809
        cache:
          id: redis
          config:
            addr: 10.81.192.4:6379
  - name: regSubscribeReciever
    path: /reg/subscribe
    handler:
      type: regSub
      plugins:
        cache:
          id: redis
          config:
            addr: "10.81.192.4:6379"
  - name: regLookUpReciever
    path: /reg/lookUp
    handler:
      type: lookUp
      plugins:
        cache:
          id: redis
          config:
            addr: "10.81.192.4:6379"
